---
title: "In-class Exercise 5"
date-modified: "last-modified"
format: html
execute: 
  echo: true
  eval: true
  warning: false
  
highlight-style: github
code:
  style: "color: red;"
---

```{r}
devtools::install_github("LukeCe/spflow")
```
```{r}
pacman::p_load(sf, sp, httr, knitr, tidyverse, Matrix, spdep, reshape2, tmap, spflow)
```


```{r}
mpsz_nb <- read_rds("data/rds/mpsz_nb.rds")
mpsz_flow <- read_rds("data/rds/mpsz_flow.rds")
mpsz_var <- read_rds("data/rds/mpsz_var.rds")
```


```{r}
mpsz_net <- spflow_network(
  id_net = "sg",
  node_neighborhood =
    nb2mat(mpsz_nb$by_contiguity),
  node_data=mpsz_var,
  node_key_column= "SZ_CODE"
)

mpsz_net
```

Create a spflow_network-class()
In **spflow** package,

```{r}
mpsz_net_pairs <- spflow_network_pair(
  id_orig_net ="sf",
  id_dest_net = "sg",
  pair_data=mpsz_flow,
  orig_key_column = "ORIGIN_SZ",
  dest_key_column = "DESTIN_SZ"

)

mpsz_net_pairs
```

```{r}
mpsz_multi_net <- spflow_network_multi(mpsz_net, mpsz_net_pairs)
mpsz_multi_net
```

Check independent variable pairs to gauge multi-colinearity
Check dependent variable relationsiip with independent variable to check for relevance


-   pair_cor() to create a correlation matrix, and
-   cor_image()

```{r}
cor_formula <- log(1+TRIPS) ~
  BUSSTOP_COUT+
  AGE7_12+
  AGE13_24+
  AGE_25_64+
  sCHOOL_COUNT +
  BUSINESS_COUNT +
  RETAILS_COUNT+
  FINSERV_COUT +
  P_(log(DISTANCE +1))


 # cor_mat <- pair_cor(
 #   mpsz_multi_net,
 #   spflow_formula = cor_formula,
 #   add_lags_x = FALSE)
 # 
 # colnames(cor_mat) <- paste0(
 #   substr(
 #     colnames(cor_mat,1,3),"..."
 #   )
 # )

```

-   MLE (default)
-   Spatial 2SLS
-   Bayesian- MCMC

```{r}
# base_model <- spflow(
#   spflow_formula = log(1+ TRIPS) ~
#     O_(BUSSTOP_COUNT +
#          AGE25_64)+
#     D_(SCHOOL_COUNT +
#          BUSINESS_COUNT +
#          RETAILS_COUNT +
#          FINSERV_COUNT) +
#     P_(log(DISTANCE +1)),
#   spflow_networks= mpsz_
# )
```



```{r}
# old_par <- par(nfrow = c(1,3),
#                mar = c(2,2,2,2))
# spflow_moran_plots(base_model)
```











